#!/usr/bin/env bash
# Auto-generated by sop-forge from SOP-HR-002. Regenerate; don't hand-edit.
# SOP: Hire for an open role: requisition to signed contract
set -euo pipefail

DRY_RUN=0
ASSUME_YES=0
FROM=""

usage() {
  cat <<USAGE
Run the "Hire for an open role: requisition to signed contract" SOP.
  --dry-run     print what would happen; run nothing
  --yes         allow destructive steps without prompting (CI)
  --from ID     resume from step ID (one of: S1 S2 S3 S4 S5 S6 S7 S8 S9 S10 S11 S12 S13 S14 S15 S16 S17 S18)
  -h, --help    this help
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --yes) ASSUME_YES=1 ;;
    --from) FROM="${2:-}"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown arg: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

# ---- helpers ----------------------------------------------------------------
c_reset=$'\033[0m'; c_blue=$'\033[34m'; c_green=$'\033[32m'
c_yellow=$'\033[33m'; c_red=$'\033[31m'; c_bold=$'\033[1m'
banner() { printf '%s\n' "${c_bold}${c_blue}==> $*${c_reset}"; }
info()   { printf '%s\n' "    $*"; }
ok()     { printf '%s\n' "${c_green}  ✔ $*${c_reset}"; }
warn()   { printf '%s\n' "${c_yellow}  ! $*${c_reset}"; }
todo()   { printf '%s\n' "${c_yellow}  TODO $*${c_reset}"; }
fail()   { printf '%s\n' "${c_red}  x step $1 failed${c_reset}" >&2
           rollback_from "$1"; exit 1; }

run_cmd() {
  info "\$ $*"
  if [ "$DRY_RUN" = 1 ]; then return 0; fi
  eval "$@"
}

confirm_destructive() {
  if [ "$ASSUME_YES" = 1 ]; then warn "destructive step auto-approved (--yes)"; return 0; fi
  if [ "$DRY_RUN" = 1 ]; then warn "destructive step (dry-run: skipped)"; return 1; fi
  printf '%s' "${c_red}  DESTRUCTIVE. Type YES to proceed: ${c_reset}"
  read -r ans; [ "$ans" = "YES" ]
}

pause_confirm() {
  if [ "$DRY_RUN" = 1 ] || [ "$ASSUME_YES" = 1 ]; then ok "$1 (auto)"; return 0; fi
  printf '%s' "  $1 [y/N] "; read -r a; case "$a" in y|Y|yes) ok "confirmed";; *) fail "manual-confirm";; esac
}

rollback_from() {
  local var="ROLLBACK_$1"
  if [ -n "${!var:-}" ]; then warn "rollback: ${!var}"; fi
}

# ---- steps ------------------------------------------------------------------
step_S1() {
  banner 'S1  Open and document the requisition'
  info 'Capture the confirmed hiring need as a requisition in the ATS: role, level, reporting line, justification, target start, and the business case. This is the record everything else hangs off.'
  run_cmd 'ats req upsert --external-id "$REQ_KEY" --role "$ROLE_TITLE" --level "$LEVEL" --manager "$HM" --justification-file ./business-case.md'
  info 'VERIFY: A requisition record exists in the ATS with role, level, reporting line, and business case.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S2() {
  banner 'S2  Approve headcount and budget'
  info 'Finance / compensation reviews the requisition against headcount plan and budget and either approves it to open or returns it. No sourcing happens before approval.'
  warn 'DECISION — a human must choose a branch:'
  echo '  - if Headcount and budget approved → go to S3'
  echo '  - if Not approved — revise or defer → go to S1'
  pause_confirm 'Recorded the decision and next step?'
  info 'VERIFY: The requisition shows an approval record with approver, date, and budgeted band.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S3() {
  banner 'S3  Finalize the job description and selection criteria'
  info 'With the hiring manager, turn the requisition into an approved job description and a structured scorecard: 6–12 job-related competencies, each with behavioral anchors. Requirements must be necessary for the role.'
  warn 'MANUAL step — perform it, then confirm.'
  pause_confirm 'Done?'
  info 'VERIFY: Every listed requirement is job-related and consistent with business necessity; the scorecard defines competencies with behavioral anchors.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S4() {
  banner 'S4  Source candidates'
  info 'Post the role to the required internal and external channels and run sourcing and referrals to build a diverse, qualified pipeline. Honor any internal-posting or pay-transparency requirements.'
  run_cmd 'ats job post --req "$REQ_ID" --channels internal,careers,linkedin --pay-range "$PAY_RANGE" --idempotency-key "$REQ_ID-post"'
  info 'VERIFY: The role is posted to all required channels and a candidate pipeline is building in the ATS.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S5() {
  banner 'S5  Screen applications'
  info 'Review applicants against the same job-related criteria and shortlist. Do not ask about criminal history at this stage where fair-chance law applies.'
  run_cmd 'ats screen run --req "$REQ_ID" --criteria ./job-related-criteria.yaml --log ./screening-log.csv'
  info 'VERIFY: All applicants are screened against the same criteria and screening decisions are logged.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S6() {
  banner 'S6  Recruiter phone screen'
  info 'Hold a consistent phone/video screen with each shortlisted candidate to confirm fit, motivation, logistics, and compensation expectations.'
  warn 'MANUAL step — perform it, then confirm.'
  pause_confirm 'Done?'
  info 'VERIFY: Each candidate is screened with the same core questions; notes are recorded in the ATS.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S7() {
  banner 'S7  Administer job-related assessments'
  info 'Where the role calls for it, administer the same validated, job-related assessment to every candidate and record results. Skip only if no assessment is used for this role.'
  run_cmd 'ats assessment send --candidates ./shortlist.csv --assessment "$ASSESSMENT_ID" --if-not-sent'
  info 'VERIFY: The same assessment is sent to all candidates for the role and results are recorded.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S8() {
  banner 'S8  Conduct structured interviews'
  info 'Run structured panel interviews using the same core questions for every candidate, scoring against the BARS scorecard. Offer reasonable accommodations on request.'
  warn 'MANUAL step — perform it, then confirm.'
  pause_confirm 'Done?'
  info 'VERIFY: Every interviewer completes an anchored scorecard with evidence notes; the same core questions were used.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S9() {
  banner 'S9  Debrief and make the selection decision'
  info 'Convene a structured debrief to reconcile scores against the anchors — not to reach consensus by social pressure — and make a documented, job-related decision. Retain the records.'
  warn 'DECISION — a human must choose a branch:'
  echo '  - if A suitable candidate is selected → go to S10'
  echo '  - if No suitable candidate — re-open sourcing → go to S4'
  pause_confirm 'Recorded the decision and next step?'
  info 'VERIFY: The decision and its rationale are documented and stored; the selection-rate is checked against the 4/5 rule.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S10() {
  banner 'S10  Complete reference checks'
  info 'Run consistent, job-related reference checks on the selected candidate and record the results before making the offer conditional.'
  warn 'MANUAL step — perform it, then confirm.'
  pause_confirm 'Done?'
  info 'VERIFY: References are completed with consistent questions and results are recorded.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S11() {
  banner 'S11  Approve compensation and extend a conditional verbal offer'
  info 'Confirm the package is approved and within band, then extend a verbal offer that is explicitly conditional on clearing screening and right-to-work checks. Follow up in writing summarizing the key terms.'
  warn 'MANUAL step — perform it, then confirm.'
  pause_confirm 'Done?'
  info 'VERIFY: Compensation is approved and within band; the conditional verbal offer and its terms are confirmed by email.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S12() {
  banner 'S12  Candidate response and negotiation'
  info 'The candidate accepts, negotiates, or declines the conditional offer. Route accordingly; re-approve compensation for any counter-offer.'
  warn 'DECISION — a human must choose a branch:'
  echo '  - if Offer accepted → go to S13'
  echo '  - if Counter-offer — re-approve and re-issue → go to S11'
  echo '  - if Declined — revisit the shortlist → go to S9'
  pause_confirm 'Recorded the decision and next step?'
  info 'VERIFY: The candidate'"'"'s response is recorded; any negotiated changes are captured before proceeding.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S13() {
  banner 'S13  Disclose, authorize, and run the background check'
  info 'Provide the standalone FCRA disclosure and obtain separate written authorization, then order the background check via the CRA. Keep the conditional offer in place while screening runs.'
  run_cmd 'cra-api order --candidate "$CANDIDATE_ID" --package standard --auth-file ./signed-authorization.pdf --idempotency-key "$CANDIDATE_ID-$REQ_ID"'
  info 'VERIFY: A signed standalone disclosure and authorization are on file before the report is ordered; the report is stored securely.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S14() {
  banner 'S14  Adjudicate the results'
  info 'Review the background and reference results. If nothing disqualifying is found, proceed to the written offer. If there is potentially disqualifying information, apply an individualized assessment and enter adverse action.'
  warn 'DECISION — a human must choose a branch:'
  echo '  - if Clears — no disqualifying, job-related information → go to S16'
  echo '  - if Potentially disqualifying information found → go to S15'
  pause_confirm 'Recorded the decision and next step?'
  info 'VERIFY: The adjudication applies job-relatedness and an individualized assessment; the rationale is documented.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S15() {
  banner 'S15  Run FCRA adverse action (only if withdrawing)'
  info 'Send the pre-adverse-action notice with a copy of the report and the Summary of Rights, wait a reasonable period for dispute (best practice at least five business days; some jurisdictions longer), then either restore the offer or send the final adverse-action notice.'
  warn 'DECISION — a human must choose a branch:'
  echo '  - if Dispute resolved in the candidate'"'"'s favor or record corrected → go to S16'
  echo '  - if Adverse action upheld — offer rescinded, revisit the shortlist → go to S9'
  pause_confirm 'Recorded the decision and next step?'
  info 'VERIFY: Both notices are documented with dates and the waiting period is observed; no irreversible internal action is taken during the waiting period.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S16() {
  banner 'S16  Extend the formal written offer'
  info 'Issue the written offer letter / employment agreement matching the approved compensation and the verbal terms, with an acceptance deadline. Route any non-standard terms to Legal first.'
  run_cmd 'esign send --template employment-agreement --candidate "$CANDIDATE_ID" --fields ./offer-terms.json --deadline "$ACCEPT_BY" --idempotency-key "$CANDIDATE_ID-offer"'
  info 'VERIFY: The sent offer matches approved terms; non-standard terms were reviewed by Legal; an acceptance deadline is set.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S17() {
  banner 'S17  Countersign and execute the agreement'
  info 'On candidate signature, countersign to fully execute the employment agreement and confirm the start date. This is the signed contract that completes the hire.'
  warn 'MANUAL step — perform it, then confirm.'
  pause_confirm 'Done?'
  info 'VERIFY: Candidate signature and employer countersignature are on file; the start date is confirmed.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

step_S18() {
  banner 'S18  Initiate right-to-work and hand off to onboarding'
  info 'Start Form I-9 and (if enrolled) E-Verify, and hand the new hire to onboarding. Section 1 is due no later than the first day; Section 2 within three business days of the start date.'
  run_cmd 'everify case ensure --employee "$EMPLOYEE_ID" --start-date "$START_DATE"'
  info 'VERIFY: Form I-9 is initiated and the onboarding handoff package is delivered to the onboarding owner.'
  if [ "$DRY_RUN" = 0 ]; then pause_confirm 'Verification passed?'; fi
}

# ---- orchestrator -----------------------------------------------------------
STEPS=(S1 S2 S3 S4 S5 S6 S7 S8 S9 S10 S11 S12 S13 S14 S15 S16 S17 S18)
started=0
[ -z "$FROM" ] && started=1
for id in "${STEPS[@]}"; do
  if [ "$started" = 0 ]; then
    if [ "$id" = "$FROM" ]; then started=1; else continue; fi
  fi
  case "$id" in
    S1) step_S1 || fail 'S1' ;;
    S2) step_S2 || fail 'S2' ;;
    S3) step_S3 || fail 'S3' ;;
    S4) step_S4 || fail 'S4' ;;
    S5) step_S5 || fail 'S5' ;;
    S6) step_S6 || fail 'S6' ;;
    S7) step_S7 || fail 'S7' ;;
    S8) step_S8 || fail 'S8' ;;
    S9) step_S9 || fail 'S9' ;;
    S10) step_S10 || fail 'S10' ;;
    S11) step_S11 || fail 'S11' ;;
    S12) step_S12 || fail 'S12' ;;
    S13) step_S13 || fail 'S13' ;;
    S14) step_S14 || fail 'S14' ;;
    S15) step_S15 || fail 'S15' ;;
    S16) step_S16 || fail 'S16' ;;
    S17) step_S17 || fail 'S17' ;;
    S18) step_S18 || fail 'S18' ;;
  esac
  ok "$id complete"
done
banner "SOP complete: Hire for an open role: requisition to signed contract"
