# Auto-generated by sop-forge from SOP-HR-002. Regenerate; don't hand-edit.
# SOP: Hire for an open role: requisition to signed contract
terraform {
  required_version = ">= 1.3"
}

# MANUAL / decision (not managed by Terraform): S2 — Approve headcount and budget
# MANUAL / decision (not managed by Terraform): S3 — Finalize the job description and selection criteria
# MANUAL / decision (not managed by Terraform): S6 — Recruiter phone screen
# MANUAL / decision (not managed by Terraform): S8 — Conduct structured interviews
# MANUAL / decision (not managed by Terraform): S9 — Debrief and make the selection decision
# MANUAL / decision (not managed by Terraform): S10 — Complete reference checks
# MANUAL / decision (not managed by Terraform): S11 — Approve compensation and extend a conditional verbal offer
# MANUAL / decision (not managed by Terraform): S12 — Candidate response and negotiation
# MANUAL / decision (not managed by Terraform): S14 — Adjudicate the results
# MANUAL / decision (not managed by Terraform): S15 — Run FCRA adverse action (only if withdrawing)
# MANUAL / decision (not managed by Terraform): S17 — Countersign and execute the agreement

# S1: Open and document the requisition
resource "null_resource" "s1" {
  triggers = {
    command = "ats req upsert --external-id \"$REQ_KEY\" --role \"$ROLE_TITLE\" --level \"$LEVEL\" --manager \"$HM\" --justification-file ./business-case.md"
  }
  provisioner "local-exec" {
    command = "ats req upsert --external-id \"$REQ_KEY\" --role \"$ROLE_TITLE\" --level \"$LEVEL\" --manager \"$HM\" --justification-file ./business-case.md"
  }
  provisioner "local-exec" {
    command = "echo VERIFY: A requisition record exists in the ATS with role, level, reporting line, and business case."
  }
}

# S4: Source candidates
resource "null_resource" "s4" {
  triggers = {
    command = "ats job post --req \"$REQ_ID\" --channels internal,careers,linkedin --pay-range \"$PAY_RANGE\" --idempotency-key \"$REQ_ID-post\""
  }
  depends_on = [null_resource.s1]
  provisioner "local-exec" {
    command = "ats job post --req \"$REQ_ID\" --channels internal,careers,linkedin --pay-range \"$PAY_RANGE\" --idempotency-key \"$REQ_ID-post\""
  }
  provisioner "local-exec" {
    command = "echo VERIFY: The role is posted to all required channels and a candidate pipeline is building in the ATS."
  }
}

# S5: Screen applications
resource "null_resource" "s5" {
  triggers = {
    command = "ats screen run --req \"$REQ_ID\" --criteria ./job-related-criteria.yaml --log ./screening-log.csv"
  }
  depends_on = [null_resource.s4]
  provisioner "local-exec" {
    command = "ats screen run --req \"$REQ_ID\" --criteria ./job-related-criteria.yaml --log ./screening-log.csv"
  }
  provisioner "local-exec" {
    command = "echo VERIFY: All applicants are screened against the same criteria and screening decisions are logged."
  }
}

# S7: Administer job-related assessments
resource "null_resource" "s7" {
  triggers = {
    command = "ats assessment send --candidates ./shortlist.csv --assessment \"$ASSESSMENT_ID\" --if-not-sent"
  }
  depends_on = [null_resource.s5]
  provisioner "local-exec" {
    command = "ats assessment send --candidates ./shortlist.csv --assessment \"$ASSESSMENT_ID\" --if-not-sent"
  }
  provisioner "local-exec" {
    command = "echo VERIFY: The same assessment is sent to all candidates for the role and results are recorded."
  }
}

# S13: Disclose, authorize, and run the background check
resource "null_resource" "s13" {
  triggers = {
    command = "cra-api order --candidate \"$CANDIDATE_ID\" --package standard --auth-file ./signed-authorization.pdf --idempotency-key \"$CANDIDATE_ID-$REQ_ID\""
  }
  depends_on = [null_resource.s7]
  provisioner "local-exec" {
    command = "cra-api order --candidate \"$CANDIDATE_ID\" --package standard --auth-file ./signed-authorization.pdf --idempotency-key \"$CANDIDATE_ID-$REQ_ID\""
  }
  provisioner "local-exec" {
    command = "echo VERIFY: A signed standalone disclosure and authorization are on file before the report is ordered; the report is stored securely."
  }
}

# S16: Extend the formal written offer
resource "null_resource" "s16" {
  triggers = {
    command = "esign send --template employment-agreement --candidate \"$CANDIDATE_ID\" --fields ./offer-terms.json --deadline \"$ACCEPT_BY\" --idempotency-key \"$CANDIDATE_ID-offer\""
  }
  depends_on = [null_resource.s13]
  provisioner "local-exec" {
    command = "esign send --template employment-agreement --candidate \"$CANDIDATE_ID\" --fields ./offer-terms.json --deadline \"$ACCEPT_BY\" --idempotency-key \"$CANDIDATE_ID-offer\""
  }
  provisioner "local-exec" {
    command = "echo VERIFY: The sent offer matches approved terms; non-standard terms were reviewed by Legal; an acceptance deadline is set."
  }
}

# S18: Initiate right-to-work and hand off to onboarding
resource "null_resource" "s18" {
  triggers = {
    command = "everify case ensure --employee \"$EMPLOYEE_ID\" --start-date \"$START_DATE\""
  }
  depends_on = [null_resource.s16]
  provisioner "local-exec" {
    command = "everify case ensure --employee \"$EMPLOYEE_ID\" --start-date \"$START_DATE\""
  }
  provisioner "local-exec" {
    command = "echo VERIFY: Form I-9 is initiated and the onboarding handoff package is delivered to the onboarding owner."
  }
}
